# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# TODO: to document
site_url: https://objective-wiles-a57b89.netlify.com/

# publish_mode: editorial_workflow

# The media_folder option specifies the folder path where uploaded files should be saved, 
# relative to the base of the repo.
media_folder: static

# The public_folder option specifies the folder path where the files uploaded by the media 
# library will be accessed, relative to the base of the built site.
public_folder: /

# A list of collections the CMS should be able to edit
collections:
  # Header
  - name: header 
    label: Header
    folder: content/layout/header
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      # Links
      - label: Menu
        name: links
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Url
            name: url
            widget: string
      # Contact Button
      - label: Contact Button
        name: contactButton
        widget: object
        fields: 
          - label: Title
            name: title
            widget: string
          - label: Url
            name: url
            widget: string
      # Logo
      - label: Logo
        name: logo
        widget: object
        fields: 
          - label: Url
            name: url
            widget: string

  # Footer
  - name: footer 
    label: Footer
    folder: content/layout/footer
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      # Logo
      - label: Logo
        name: logo
        widget: object
        fields: 
          - label: Url
            name: url
            widget: string
      - label: Copyrights
        name: copyrights
        widget: string
      # Social links
      - label: Social Links
        name: socialLinks
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Url
            name: url
            widget: string
          - label: Icon
            name: icon
            widget: string
      # Links 1
      - label: Menu 1
        name: links
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Url
            name: url
            widget: string
      # Links 2
      - label: Menu 2
        name: links2
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Url
            name: url
            widget: string

  # Home page 
  - name: index-page
    label: Index Page
    folder: content/pages/index
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      # Hero
      - label: Hero
        name: hero
        widget: object
        fields:
          - label: Text 1
            name: text1
            widget: string
          - label: Text 2
            name: text2
            widget: string
          - label: Text 3
            name: text3
            widget: string  
          - label: Text
            name: text
            widget: string   
      # Presentation                     
      - label: Presentation
        name: presentation
        widget: object
        fields:
          - label: Services
            name: services
            widget: list
            fields:
              - label: Text
                name: text
                widget: string 
              - label: Icon
                name: icon
                widget: string 
          - label: Buttons
            name: buttons
            widget: list
            fields:
              - label: Title
                name: title
                widget: string 
              - label: Url
                name: url
                widget: string                 
      # News                   
      - label: News
        name: news
        widget: object
        fields:
          - label: Title
            name: title
            widget: string 
          - label: Sub Title
            name: subTitle
            widget: string           
          - label: Button
            name: button
            widget: object
            fields:
              - label: Title
                name: title
                widget: string 
              - label: Url
                name: url
                widget: string 
      # Projects                   
      - label: Projects
        name: projects
        widget: object
        fields:
          - label: Title
            name: title
            widget: string 
          - label: Sub Title
            name: subTitle
            widget: string      
          - label: Text
            name: text
            widget: text
          - label: Projects
            name: projects
            widget: list
            fields:
              - label: Title
                name: title
                widget: string 
              - label: Text
                name: text
                widget: string  
              - label: Image Key
                name: imageKey
                widget: string 
  # Services page 
  - name: services-page
    label: Services Page
    folder: content/pages/services
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Slug
        name: slug
        widget: string    
      # Intro    
      - label: Intro
        name: intro
        widget: object
        fields: 
          - label: Title
            name: title
            widget: string
          - label: Sub Title
            name: subTitle
            widget: string
          - label: Text
            name: text
            widget: text
      # Contact Button    
      - label: Contact Button
        name: contactButton
        widget: object
        fields: 
          - label: Title
            name: title
            widget: string
          - label: Url
            name: url
            widget: string
      # Services
      - label: Services
        name: services
        widget: list
        fields: 
          - label: Icon
            name: icon
            widget: string
          - label: Title
            name: title
            widget: string    
          - label: Text
            name: text
            widget: string                        
          - label: Tags
            name: tags
            widget: list