# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# TODO: to document
site_url: https://objective-wiles-a57b89.netlify.com/
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections: # A list of collections the CMS should be able to edit
  # Header
  - name: header 
    label: Header
    folder: content/layout/header
    create: false
    delete: false
    fields:
      # Links
      - label: Menu
        name: links
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Url
            name: url
            widget: string
      # Contact Button
      - label: Contact Button
        name: contactButton
        widget: object
        fields: 
          - label: Title
            name: title
            widget: string
          - label: Url
            name: url
            widget: string
      # Logo
      - label: Logo
        name: logo
        widget: object
        fields: 
          - label: Url
            name: url
            widget: string

  # Footer
  - name: footer 
    label: Footer
    folder: content/layout/footer
    create: false # Prevent users from creating documents in this collection
    delete: false # Prevent users from deleting documents in this collection
    fields:
      - {label: "Title", name: "title", widget: "string"}     
  # Home page 
  - name: index-page
    label: Index Page
    folder: content/pages/index
    create: false # Prevent users from creating documents in this collection
    delete: false # Prevent users from deleting documents in this collection
    # editor:
    #   preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}