---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: content/layout/header
  label: header
  create: documents
  match: "**/*"
upload_dir: static/images
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GATSBY_WEBPACK_PUBLICPATH=/
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npx run gatsby develop -p 8080 -H 0.0.0.0
