---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: content/layout
  label: Layout
  create: documents
  match: "**/*"
upload_dir: static/images
public_path: '/'
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: yarn run forestry:publish
  publish_command: yarn run forestry:publish
  preview_env:
  - PATH_PREFIX=/
  publish_env:
  - PATH_PREFIX=/
  preview_output_directory: public
  output_directory: public
  instant_preview_command: yarn run forestry:preview
  install_dependencies_command: yarn
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
